### ISSUE TITLE
Minimum amount of upload interval

### ISSUE THREAD

**Issue by jurvanwijk** [Xorfor/Domoticz-PWS-Plugin#12]
Hello,

What is the minimum amount of seconds for the upload interval?

**Comment by Xorfor** [comment]
To be honest, I didn't experiment with that. As far as I know there is a minimum to Ecowitt of 60 sec. and I think also to WeatherCloud and Wunderground.

I know that for handling events in the Python Plugin system there is an interval of 10 sec. 
I guess that will be the minum. But according to other users, they use the default of 60 sec. which is also for me a nice interval.

**Comment by jurvanwijk** [comment]
Okay, thanks for your reaction!
