### ISSUE TITLE
PWS Soil moisture

### ISSUE THREAD

**Issue by codystoica** [Xorfor/Domoticz-PWS-Plugin#14]
Hi, I know you no longer provide maintenance for Domoticz PWS plugin.  But if you have time and you want to add support for soil moisture I would be very grateful.

**Comment by Xorfor** [comment]
No problem. Do you have a json example from your PWS?

**Comment by Xorfor** [comment]
Just did a commit with the new Soilmoisture sensor. I am not able to test this. Please let me know your experience

**Comment by codystoica** [comment]
Thank you, it works perfectly, you are the best!

**Comment by Xorfor** [comment]
Thnx!
