### ISSUE TITLE
add support for the ws90 sensor array

### ISSUE THREAD

**Issue by betogar85** [Xorfor/Domoticz-PWS-Plugin#19]
Hi, I recently changed my console's matrix sensor due to a glitch, currently I have the ws90 sensor which is not supported by the plugin, I know it is not maintained anymore but if you have the time and want to add support I would be very grateful
this is the log

data: {'PASSKEY': '5214AB4342302A041AD0A4FC35000A56', 'stationtype': 'EasyWeatherPro_V5.1.1', 'runtime': '1', 'dateutc': '2023-01-25+00:15:47', 'tempinf': '78.8', 'humidityin': '41', 'baromrelin': '29.811', 'baromabsin': '28.523', 'tempf': '72.3', 'humidity': '45', 'winddir': '8', 'windspeedmph': '0.00', 'windgustmph': '7.83', 'maxdailygust': '8.72', 'solarradiation': '5.92', 'uv': '0', 'tf_co2': '70.9', 'humi_co2': '59', 'pm25_co2': '1.6', 'pm25_24h_co2': '3.3', 'pm10_co2': '2.3', 'pm10_24h_co2': '3.8', 'co2': '636', 'co2_24h': '483', 'lightning_num': '0', 'lightning_time': '1673272365', 'lightning': '34', 'rrain_piezo': '0.000', 'erain_piezo': '0.000', 'hrain_piezo': '0.000', 'drain_piezo': '0.000', 'wrain_piezo': '0.000', 'mrain_piezo': '0.000', 'yrain_piezo': '0.000', 'ws90cap_volt': '0.3', 'ws90_ver': '126', 'wh25batt': '0', 'wh57batt': '5', 'co2_batt': '6', 'wh90batt': '3.22', 'freq': '433M', 'model': 'HP2550_Pro_V1.8.0', 'interval': '20'}

![214449986-0b260df4-6362-4417-bcf0-207cff7e1b33](https://user-images.githubusercontent.com/116471288/216491112-750a0671-c23b-43c9-996a-eb60ff5910cf.png)

**Comment by Xorfor** [comment]
Some questions:
1. Have you any idea about which value contains the rainrate: `rrain_piezo` or `erain_piezo`?
2. What is `tf_co2`?
3. I guess `humi_co2` is outdoor and `humidity` is indoor?

**Comment by betogar85** [comment]
today's log:

Data: 'b'PASSKEY=5214AB4342302A041AD0A4FC35000A56&stationtype=EasyWeatherPro_V5.1.1&runtime=4&dateutc=2023-02-06+21:53:39&tempinf=84.6&humidityin=39&baromrelin=29.802&baromabsin=29.787&tempf=85.5&humidity=33&winddir=135&windspeedmph=3.80&windgustmph=13.65&maxdailygust=14.99&solarradiation=409.79&uv=3&tf_co2=70.0&humi_co2=71&pm25_co2=1.4&pm25_24h_co2=2.9&pm10_co2=1.9&pm10_24h_co2=3.5&co2=1546&co2_24h=1114&lightning_num=0&lightning_time=&lightning=&rrain_piezo=0.000&erain_piezo=0.000&hrain_piezo=0.000&drain_piezo=0.004&wrain_piezo=0.004&mrain_piezo=0.028&yrain_piezo=0.087&ws90cap_volt=5.3&ws90_ver=126&wh25batt=0&wh57batt=5&co2_batt=6&wh90batt=3.22&freq=433M&model=HP2550_Pro_V1.8.0&interval=20''

![Captura de pantalla 2023-02-06 160039](https://user-images.githubusercontent.com/116471288/217097725-4528f76c-d001-408d-b27a-2d67cd0619ee.png)

![Captura de pantalla 2023-02-06 160131](https://user-images.githubusercontent.com/116471288/217097763-0fef7b36-1202-43cb-b6a9-1f9127bce196.png)

rrain_piezo - rainrate
erain_piezo - rain event

tf_co2 - wh45 sensor that measures co2, pm2.5 and pm10, temp and humidity

**Comment by Xorfor** [comment]
I just added support for the WS90 sensor. Please test asap, because I don't have this device!!!
Let me know the results.

**Comment by betogar85** [comment]
It's working without errors, thank you very much!
