### ISSUE TITLE
UV Warning triggered by Eventsystem (Blockly script)

### ISSUE THREAD

**Issue by RicardP** [Xorfor/Domoticz-PWS-Plugin#2]
Hi,

I added the UV Waring device and got UV Index 1 warning at totally cloudy and foggy day, when checking the log I discovered that my Heating scripts in Blockly is involved in changing UV Warning state. Checking those Blockly scripts I cannot see any logic's causing this. 

![clip](https://user-images.githubusercontent.com/21274628/73871718-a28cb200-484e-11ea-9c37-65f57307597d.JPG)

**Comment by Xorfor** [comment]
Is this problem related to malfunction of the PWS plugin? If not, please use the Domoticz forum to ask other users. Also, without any explanation, screendump, etc. of the used blockly script, it is hard to help you.

**Comment by RicardP** [comment]
Hi, the UV-Warning device is created by yours Domoticz-PWS-Plugin, along all the others weather devices. 

![a](https://user-images.githubusercontent.com/21274628/74032515-712df680-49b4-11ea-85e2-9805ba3156a9.JPG)

The EventSystem/xxxx triggers is seen within the UV-Warning device log. I wonder if it can be some errors in the UV-Warning calculate code? Maybe you can take a quick look :)

**Comment by Xorfor** [comment]
The UV Alert looks to the value of the UVI (UV index), and is not calculated.

And again, I need more info, to help you, eg.:

What is the relation to your Blockly scripts you described?
Do you see messages in the log related to this UV Alert device?
Does the UVI device give the same values as your PWS?
etc...

**Comment by Xorfor** [comment]
Didn't get any further information.
