### ISSUE TITLE
Update Easyweather V1.2.2

### ISSUE THREAD

**Issue by pierstitus** [Xorfor/Domoticz-PWS-Plugin#3]
Hi, I just bought a Alecto WS-5500, partly because of this plugin. However mine has EasyWeatherV1.2.2, do you know how to update to 1.4?

On boot the display shows ver 2 1.06 65 868 EU

On the back the number is WS5500-000146, could have meant 1.4.6

Thanks for the good work!

**Comment by Xorfor** [comment]
Does the plugin work with your Alecto WS-5500? 
One of the created devices the PWS - Station will show you information like:

192.168.0.249 (EasyWeatherV1.4.7): Wunderground

This device gives you the current version of EasyWeather used in your weatherstation.
My PWS updates with the help of WS View on my tablet or phone. The software detects the new version and will upload this new version to your PWS.

**Comment by pierstitus** [comment]
I couldn't find it in WS View, but tried the awnet app (rebranded version of ambientweather) and that did update the PWS from v1.2.2 to v1.4.7. Maybe I just missed the button because it's just under Wunderground setup. Now I can use WS View to configure. Thanks!
