### ISSUE TITLE
Calibration of Barometer

### ISSUE THREAD

**Issue by RicardP** [Xorfor/Domoticz-PWS-Plugin#4]
Hi! I tried to calibrate Barometric sensor but the inserted offset did not make any change. So I thought it was a native Domoticz sensor issue... :)

https://github.com/domoticz/domoticz/issues/4096

**Comment by Xorfor** [comment]
What gizmocuz is telling, '... the python script directly access the database and does not go via the normal internal route...'. Is NOT true, I am using the standard python calls from Domoticz. He probably didn't look into the Python PWS plugin code.

But you are right. The adjustments are not used in Domoticz, at least by the Domoticz Python calls. Not only for the barometer, but also for temperature is not working.

I will do some more investigation and keep you informed.

**Comment by Xorfor** [comment]
It seems that ther was already a discussion about this:

https://www.domoticz.com/forum/viewtopic.php?f=65&t=25853&p=199178&hilit=adjustment#p199178

**Comment by Xorfor** [comment]
Look at the discussion at https://github.com/domoticz/domoticz/pull/2899. It seems that the Domoticz programmers do not agree how to store the values. My opinion is also to store the raw data and use the adjustment to display the corrected data.
To be sure that nothing changed the last months, I did ask the status about this issue on: https://www.domoticz.com/forum/viewtopic.php?f=65&t=32354

Sorry, that is all I can do for this moment :(

**Comment by RicardP** [comment]
Hi @Xorfor Many thanks for looking into this. I am not in a hurry but it would be valuable to get it fixed of course :)

Many thanks for your PWS plugin, it woks great!

**Comment by gizmocuz** [comment]
@Xorfor , "It seems that the Domoticz programmers do not agree how to store the values" ?
Sorry, that is a bit harsh to say ! That message did for instance not reach me.
The main issue is that internally the updates from the python plugin are directly stored inside the database and do not follow the normal path that all internal plugins use
(I am not the implementer of this)
In order to support the adjustments we should (at least for temp/hum/baro/...) use the internal path.
I could build this, but my python knowledge is very poor !
If you like to help with this, please contact me on slack, or via a PM on the forum

In the feature we should replace this:

[unit.TEMP, "Temperature", 80, 5, {}, used.YES],

with

Domoticz.SendTempSensor(plugin_hw_id, idx, 20.4)

**Comment by Xorfor** [comment]
@gizmocuz I did sent a PM to you on the forum, but still in my Outbox. You Inbox full?

**Comment by gizmocuz** [comment]
@Xorfor , I get more then 50 mails per day and only look on queue.
I see your mail, and two deleted mails
I will reply by PM

**Comment by RicardP** [comment]
@gizmocuz @Xorfor Just curious if there is any further considerations on the calibration issue? I do not know what your PMs resulted in :)

Cheers!

**Comment by Xorfor** [comment]
@RicardP As far as I know, nothing is changed in Domoticz to implement this.

**Comment by Xorfor** [comment]
Stopped further development of this plugin

**Comment by pipiche38** [comment]
> @Xorfor , "It seems that the Domoticz programmers do not agree how to store the values" ?
> Sorry, that is a bit harsh to say ! That message did for instance not reach me.
> The main issue is that internally the updates from the python plugin are directly stored inside the database and do not follow the normal path that all internal plugins use
> (I am not the implementer of this)
> In order to support the adjustments we should (at least for temp/hum/baro/...) use the internal path.
> I could build this, but my python knowledge is very poor !
> If you like to help with this, please contact me on slack, or via a PM on the forum
> 
> In the feature we should replace this:
> 
> [unit.TEMP, "Temperature", 80, 5, {}, used.YES],
> 
> with
> 
> Domoticz.SendTempSensor(plugin_hw_id, idx, 20.4)

@gizmocuz ready to help/support you on this matter. This will really bring a lot of value to the Python Plugins
