### ISSUE TITLE
Forward to Wunderground

### ISSUE THREAD

**Issue by glsf91** [Xorfor/Domoticz-PWS-Plugin#6]
Should be nice if there is an option to forward the data also to Wunderground. So then we have both domoticz and Wunderground.

**Comment by Xorfor** [comment]
That is not possible. You can only connect a PWS to 1 destination. It is more a limitation of EasyWeather.

**Comment by glsf91** [comment]
> That is not possible. You can only connect a PWS to 1 destination. It is more a limitation of EasyWeather.

I understand but the question was if the plugin can forward this?
