### ISSUE TITLE
Garni 2055 Arcus support

### ISSUE THREAD

**Issue by bramhut** [Xorfor/Domoticz-PWS-Plugin#8]
Hello,

I have tried your guide to connect a Garni 2055 to my WiFi with WS View and WS Tool. However, none of the weather stations listed in the apps seem to work. When I set the WiFi up in the browser (the weather station is in AP mode), I can connect to my WiFi network, altough the option to set a custom URL is not functioning ( I used the URL provided in the picture: ip:port/weatherstation/updateweatherstation.php? ). The Domoticz side seems to work correctly.

What is the issue here?

**Comment by Xorfor** [comment]
Please use WS View to setup the wifi connection! And can you show me the log of the plugin?

**Comment by bramhut** [comment]
I have tried setting up the wifi connection with WS View. None of the weather stations that were listed worked. They all ended with a timeout. It seems that WS View is trying to find specific wifi networks with EasyWeather in the SSID (I could be wrong here). However, the SSID of the Garni 2055 starts with PWS-xxxxxx. Could that be an issue?

Here is the log of the plugin when it is added to domoticz:
`2020-08-28 11:18:24.507 Status: (Weerstation) Stop directive received.`
`2020-08-28 11:18:24.507 Status: (Weerstation) Exiting work loop.`
`2020-08-28 11:18:24.708 Status: (Weerstation) Stopping threads.`
`2020-08-28 11:18:24.708 Status: (Weerstation) Stopped.`
`2020-08-28 11:18:24.708 Status: (Weerstation) Started.`
`2020-08-28 11:18:24.907 Status: (Weerstation) Entering work loop.`
`2020-08-28 11:18:24.908 Status: (Weerstation) Initialized version 1.0.9, author 'Xorfor'`

**Comment by Xorfor** [comment]
As long as your PWS is not connected to your wifi, the Domoticz plugin will not receive any data!!!

WS View is not trying to find specific networks!!! 
WS View is straight forward. Connect your mobile/tablet to your wifi, start WS View and click on Configure new device, select the correct PWS and follow the instructions. WS View will search on your network for an EasyWeather supported device and connect it to your network.
WS View will show your PWS with an ip address. Try to ping from the Domoticz server to your PWS. If the ping is succesfull, then your are ready to configure PWS to your Domoticz server.

**Comment by bramhut** [comment]
Sorry, I think I wasn't clear enough. The PWS can easily be connected to my wifi network using the supplied instructions from Garni. However, connecting the PWS using WS View to my wifi was not succesful (the PWS was in AP mode and my smartphone was connected to the wifi network of the PWS).  None of the PWS models that can be chosen in WS View work. 

> ... select the correct PWS ...

There is also no option for the Garni 2055, which could explain the reason why it is not working. 

Also, in the instructions in WS View, it clearly states that I need to connect to a EasyWeather wifi network, which the PWS does not have. The SSID of the PWS has the form: PWS-xxxxxx.

Hopefully you understand the issue now.

**Comment by bramhut** [comment]
In these pictures you can also see that the Garni 2055 Arcus is not listed in WS View
![WhatsApp Image 2020-08-28 at 21 39 16](https://user-images.githubusercontent.com/13022463/91609166-318e2280-e977-11ea-9113-e54b2f16db0f.jpeg)
![PWS](https://user-images.githubusercontent.com/13022463/91609176-3521a980-e977-11ea-9cb8-10f52613e380.png)

**Comment by Xorfor** [comment]
Correct. Also mine is not listed. Take the best match!!! I suggest the second one

**Comment by bramhut** [comment]
Thank you for your help!

> You said: 'The PWS can easily be connected to my wifi network using the supplied instructions from Garni.'
> Is that done by a Garni tool, or something like that?

I connected to the wifi network of the PWS and then used the gateway IP adres to access the setup page of the Garni. There I could fill in the SSID and password of my home wifi network. 
There is also an option to connect to an URL, which in the Garni manual is mentioned that it is reserved for an user supplied server. I guess it also should be possible to add the URL of the domoticz plugin here? I have tried different URL's like ip:port/weatherstation/updateweatherstation.php? However without succes...

Setup page of the PWS:
![WhatsApp Image 2020-08-28 at 22 16 24](https://user-images.githubusercontent.com/13022463/91611691-27225780-e97c-11ea-9d4a-a41d6f44ce36.jpeg)

I will post a question on the Garni forum to see if anybody is familiar with connecting the PWS to wifi using WS View.

Again, thanks for the help!

**Comment by Xorfor** [comment]
Please try the following steps:

Try to ping from your Domoticz server to your PWS
If succesfully, try as url: **http://**<ip address Domoticz server>:5000/...

**Comment by bramhut** [comment]
I have tried pinging the PWS from Domoticz server, without succes. Ping replying is probably not enabled in the firmware of the PWS. However, I can see on my router that the PWS is connected.
For some reason, the URL size is limited in the config page of the PWS. The URL is a couple of charachters too long...
I will have a look to find a way to shorten the URL tomorrow...

**Comment by TheNetopyr** [comment]
I had a similar issue with the PWS; within the PWS you should just add the IP (no port number, since it won't work). on my domoticz server I added a rule like: iptables -t nat -A PREROUTING -s [IP of PWS] -p tcp --dport 80 -j DNAT --to-destination [IP of Domoticz]:5000

**Comment by bramhut** [comment]
Thank you! That did the trick. Maybe it is a good idea to add this to the installation instruction so other Garni 2055 owners don't encounter the same issue.

**Comment by Xorfor** [comment]
> I had a similar issue with the PWS; within the PWS you should just add the IP (no port number, since it won't work). on my domoticz server I added a rule like: iptables -t nat -A PREROUTING -s [IP of PWS] -p tcp --dport 80 -j DNAT --to-destination [IP of Domoticz]:5000

I don't know this Garni tool. But if you don't use _iptables_ but enters port 80 in mine plugin, does that also work?

**Comment by bramhut** [comment]
It may work, however I'm already using port 80 so will a lot of other people. So it may be a good idea to at least include the instruction how to use a different port if necessary.

**Comment by Xorfor** [comment]
Added some instructions to use the Garni Technology app to connect the PWS to Domoticz.
