### ISSUE TITLE
Sainlogic WS3500 confirmed

### ISSUE THREAD

**Issue by pixelmagic66** [Xorfor/Domoticz-PWS-Plugin#9]
Hi,

Great work on this, I have a Sainlogic WS3500 station from Amazon (https://www.amazon.nl/Wunderground-Weerstation-buitensensor-weersvoorspelling-kleurendisplay/dp/B07F2GQDW2) and I can confirm that this station also works with this software.

**Comment by Xorfor** [comment]
Thnx a lot for this info!!! The Sainlogic WS3500 is added.
